### ISSUE TITLE
MAPA MENTAL_ WEB 3.0_RIGOBERTORAMIREZNICOLAS

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/mapa-mental-web-3-Rigoberto2001#1]
![MAPAMENTAL_RIGOBERTORAMIREZNICOLAS](https://user-images.githubusercontent.com/79929662/160749102-1d2bcbd1-4767-47b3-bf10-9975e8874c5e.png)

**Comment by christopheremv** [comment]
calificación :19 de 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
